server:
 port: 8280
 
spring:
  application:
    name: vet-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:root}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/vet_service}
    username: ${DB_USER:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

logging:
  file:
    name: logs/vetservice.log   
      
management:
  endpoints:
    web:
      exposure:
        include: "*"  